services:
  - type: web
    name: throttl-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /uptime
    envVars:
      - key: REDIS_URL
        sync: false
